import { Inter } from "next/font/google";
import Footer from "../../components/Footer/components/Footer";
import Header from "../../components/Header/components/Header";
import "../globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen ${inter.className}`}>
        <div className="mx-auto max-w-[1536px]">
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
